# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cd39689f9892c36d9809d189bfc8a46e33a688ef8e744d94192fc79e3a69374c696a70d40469d3431160f5e34819d5fe56755b631ed4807dfa4a1522ee03edf

test:
  secret_key_base: 4b4a5bbe6e3319960577a59a487ba91dd92dd3a7519d93c0ea2099bb71795d714975a65947688090cf3aea456fad8d93c665f07c7172bed4f3842a03bb94f902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
